[env:esp32]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

; Libraries
lib_deps =
    adafruit/DHT sensor library@^1.4.4
    adafruit/Adafruit Unified Sensor@^1.1.14
    bblanchon/ArduinoJson@^7.0.0

; Upload settings
upload_speed = 921600
upload_protocol = esptool

; Build settings
build_flags =
    -DBOARD_ESP32
